import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cachedFetch = (input: any, init?: any): Promise<Response> => {
    return fetch(input, {
        ...init,
        cache: process.env.NODE_ENV === "development" ? "no-store" : "force-cache",
    });
};

storyblokInit({
    accessToken: process.env.STORYBLOK_TOKEN,
    use: [apiPlugin],
    apiOptions: {
        fetch: cachedFetch,
    },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <StoryblokProvider>
          <html lang="en">
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <header className="sticky top-0 bg-white shadow-md z-10">
              <nav className="container mx-auto px-4 w-full py-8 flex justify-between">
                  <Link href={"/"}>Home</Link>
                  <Link href={"/albums"}>Albums</Link>
                  <Link href={"/artists"}>Artists</Link>
              </nav>
          </header>
          {children}
          <footer>
              <nav className="container mx-auto px-4 gap-8 w-full py-8 flex justify-center">
                  <Link href={"/imprint"}>Imprint</Link>
                  <Link href={"/legal-notice"}>Legal Notice</Link>
                  <Link href={"/contact"}>Contact</Link>
              </nav>
          </footer>
          </body>
          </html>
      </StoryblokProvider>
  );
}
